version: '3.3'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3002:3001  # Maps internal 3001 to external 3002 (to avoid conflict with Homepage)
    restart: always
