services:
  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:latest
    container_name: zerobyte
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    ports:
      - "4096:4096"
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      - TZ=Asia/Beirut
      - APP_SECRET=your_generated_secret_here
      - BASE_URL=http://192.168.1.10:4096

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/zerobyte:/var/lib/zerobyte
      - /var/run/docker.sock:/var/run/docker.sock #For ZeroByte to be able to stop other containers

      # This mounts ALL your Docker data (including Portainer) into ZeroByte
      - /var/lib/docker:/docker_data:ro
      - /home/omar/backups:/backups_folder
